version: "3.8"
services:
  cell-tower-locator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        - "API_KEY=${API_KEY}"
    volumes:
      - "./geo_data:/cell-tower-locator/geo_data"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.request.rule=Host(`${CELL_TOWER_LOCATOR_HOST}`)"
      - "traefik.http.routers.request.tls=true"
      - "traefik.http.routers.request.tls.certresolver=tls"
      - "traefik.http.services.request.loadbalancer.server.port=5000"

networks:
  traefik:
    external: true

volumes:
    geo_data:
